version: "3.7"
services:
  rp:
    image: nginx:1.17.4-alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/rp.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
  app1:
    image: nginx:1.17.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
networks:
  default:
