version: "3.7"
services:
  rp:
    image: nginx:1.17.4-alpine
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:80
    volumes:
      - ./nginx_rp.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
  app1:
    image: nginx:1.17.4-alpine
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./nginx_app.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
networks:
  default:
