apache:
    build: .
    volumes:
        - .:/shared
    environment:
        APACHE_VERSION: 2.4.16
        APR_VERSION: 1.5.2
        APR_UTIL_VERSION: 1.5.4
    command: /bin/sh ./build_apache.sh
