apache:
    build: .
    volumes:
        - .:/shared
    environment:
        APACHE_VERSION: 2.4.16
        APR_VERSION: 1.5.2
        APR_UTIL_VERSION: 1.5.4
    command: /bin/sh ./apache/./build.sh
redis:
    build: .
    volumes:
        - .:/shared
    environment:
        REDIS_VERSION: 3.2.8
    command: /bin/sh ./redis/./build.sh
handlersocket:
    build: .
    volumes:
        - .:/shared
    environment:
        MYSQL_VERSION: 5.6.19
        HANDLERSOCKET_VERSION: 1.1.1
    command: /bin/sh ./handlersocket/./build.sh
