name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: [amazon-ssm-agent]
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: docker build ${{matrix.images}} --tag seiji/${{matrix.images}}:latest
    - name: Login docker
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - name: Push image
      run: docker push seiji/${{matrix.images}}:latest
